### ISSUE TITLE
question - two stores, sharing state

### ISSUE THREAD

**Issue by Jacknq** [HerringtonDarkholme/kilimanjaro#12]
Hi, at first, thanks for you amazing work, I really like this library,currently Im developing vue ts .net core template ..  and yes I WANT to use it production :)  and no I am not freak..
Question here : 
Lets say I have two stores, one is stored in localstorage another one is simple. But I want to expose only one store at the end (I know I can export them separately), with mixed getters from lets say store2 on store. How to do that?

```ts

const state : storeData = { 
 count: 0, isAuth: false,
 token:'', lang: 'de', 
location:'EN', 
servurl : host

};
const storeData : storeData = JSON.parse(storage.getItem(storage.C_ENV_KEY));
const cmpdStore : cmstore= {store:state,db:null};
var store2 = create(cmpdStore).getter('db',s => { return s.db;  })
.mutation('dbset',s => (n: cl.dbCloud)=> { s.db = n; } ); //-I want to observe this complex value
//var { getters, commit } = getHelper(store2)
cmpdStore.db = new cl.dbCloud(state.servurl, state.token);


var store = create(storeData)//.
  .getter('count', s => { return s.count  })
  .getter('location', s => { return s.location  })
  .getter('vars', s => { return s  })
  .getter('db', s => { return cmpdStore.db;  }) //how to create getter on pointing to second store (store2) here?



```

**Comment by HerringtonDarkholme** [comment]
Use module.
https://github.com/HerringtonDarkholme/kilimanjaro/blob/master/test/index.ts#L225
