### ISSUE TITLE
Anything I need to worry about the compatibility with av-ts@0.7.0?

### ISSUE THREAD

**Issue by whitetrefoil** [HerringtonDarkholme/kilimanjaro#13]
Let me guess, is at-ts@0.7.0 just a compatibility fix of vue@2.2.0? So there's nothing to do with kilimanjaro, isn't it?

**Comment by HerringtonDarkholme** [comment]
> is at-ts@0.7.0 just a compatibility fix of vue@2.2.0?

Yes.

>  So there's nothing to do with kilimanjaro

I have not tested it. But it should work.

**Comment by whitetrefoil** [comment]
Great!  I'll let you know if there's anything wrong when I'm using it.
