### ISSUE TITLE
Is current version compatible with av-ts@^0.6.0?

### ISSUE THREAD

**Issue by whitetrefoil** [HerringtonDarkholme/kilimanjaro#7]
I've upgraded av-ts in my project to the latest, so now npm started to warn about the peer dep. version.

I'm not sure if there's any change really breaks anything. Should I just ignore it or rollback to @^0.5.0 till kilimanjaro get upgraded?

**Comment by HerringtonDarkholme** [comment]
I'm scheduling a new update, please wait a moment, won't be long :)

You can refer to changelogs for av-ts. I think there is no breaking change.

**Comment by HerringtonDarkholme** [comment]
Published 0.6.0.

I'm considering introducing a large breaking change 😢 .

The new TypeScript type has amazing new typing feature, I really want to use them.

**Comment by whitetrefoil** [comment]
Big fan of new feature here ~

As a JS dev, breaking change is life style of every day 😹

Anyway, it will be much better if changes come earlier rather than after
the project grow into a uncontrollable monster...

2016年12月14日 16:47，"(´・ω・｀)" <notifications@github.com>写道：

Published 0.6.0.

I'm considering introducing a large breaking change 😢 .

The new TypeScript type has amazing new typing feature.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HerringtonDarkholme/kilimanjaro/issues/7#issuecomment-266976925>,
or mute the thread

**Comment by HerringtonDarkholme** [comment]
The breaking change I want to introduce has clear migration path.

I think @whitetrefoil you are the only user other than me. Let's just trying out new possibility.

~~Again, I don't recommend to use kilimanjaro in production, if you are using it in hobby project then feel free~~

**Comment by whitetrefoil** [comment]
Not using any TS code in production yet.  But I do plan to make something work in production once I got the whole stack work.  While "something" has only one user...😂

**Comment by HerringtonDarkholme** [comment]
@whitetrefoil I found a completely different approach to integrate Vue with TypeScript.
I will put my new finding in a different repo. So no breaking change will in av-ts or kilimanjaro. Feel safe.
