### ISSUE TITLE
Why do you say this should not be used in production?

### ISSUE THREAD

**Issue by Evertt** [HerringtonDarkholme/kilimanjaro#8]
And when do you think it can be?

**Comment by HerringtonDarkholme** [comment]
It uses too many type level constructs that most developers in the community do not understand. That's all.

Actually the implementation is very simple, the test covers source well. And I personally have used in production and worked well. But the community is not ready for this.

**Comment by Evertt** [comment]
Well that's definitely true for me, because I don't know shit about typescript (yet). So is it that you recommend against using it if you don't understand how it works, because then it's very hard to debug?
